<?php
/*
    This file is part of Symbiose Community Edition <https://github.com/yesbabylon/symbiose>
    Some Rights Reserved, Yesbabylon SRL, 2020-2025
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

namespace discope\followup;

use equal\orm\Model;

class TaskModel extends Model {

    public static function getDescription(): string {
        return "A task is generated from a task model when an entity is created or change status.";
    }

    public static function getColumns(): array {
        return [

            'name' => [
                'type'              => 'string',
                'description'       => "Name of the task model.",
                'required'          => true
            ],

            'description' => [
                'type'              => 'string',
                'usage'             => 'text/plain',
                'description'       => "Description of the task model."
            ],

            'entity' => [
                'type'              => 'string',
                'description'       => "Namespace of the concerned entity.",
                'required'          => true
            ],

            'tasks_group_name' => [
                'type'              => 'string',
                'description'       => "Name of the tasks group.",
                'help'              => "Allows to group the tasks."
            ],

            'trigger_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'discope\followup\TaskEvent',
                'description'       => "The trigger event associated with the task model."
            ],

            'deadline_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'discope\followup\TaskEvent',
                'description'       => "The deadline event associated with the task model."
            ],

            'tasks_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'discope\followup\Task',
                'foreign_field'     => 'task_model_id',
                'description'       => "The tasks generated by the task model."
            ]

        ];
    }
}
