<?php
/*
    This file is part of Symbiose Community Edition <https://github.com/yesbabylon/symbiose>
    Some Rights Reserved, Yesbabylon SRL, 2020-2025
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

namespace sale\booking\followup;

use equal\orm\Model;

class TaskModel extends Model {

    public static function getDescription(): string {
        return "A task is generated from a task model when an entity is created for a specific center office.";
    }

    public static function getColumns(): array {
        return [

            'name' => [
                'type'              => 'string',
                'description'       => "Name of the task model.",
                'required'          => true
            ],

            'description' => [
                'type'              => 'string',
                'usage'             => 'text/plain',
                'description'       => "Description of the task model."
            ],

            'entity' => [
                'type'              => 'string',
                'description'       => "Namespace of the concerned entity.",
                'required'          => true
            ],

            'task_group' => [
                'type'              => 'string',
                'description'       => "Name of the task group.",
                'help'              => "Allows to group the tasks."
            ],

            'trigger_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'sale\booking\followup\TaskEvent',
                'description'       => "The trigger event associated with the task model."
            ],

            'deadline_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'sale\booking\followup\TaskEvent',
                'description'       => "The deadline event associated with the task model."
            ],

            'tasks_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'sale\booking\followup\Task',
                'foreign_field'     => 'task_model_id',
                'description'       => "The tasks generated by the task model."
            ],

            'center_offices_ids' => [
                'type'              => 'many2many',
                'foreign_object'    => 'identity\CenterOffice',
                'foreign_field'     => 'task_models_ids',
                'rel_table'         => 'identity_center_office_rel_sale_task_model',
                'rel_foreign_key'   => 'center_office_id',
                'rel_local_key'     => 'task_models_id',
                'description'       => "Center offices associated with the task model.",
                'help'              => "When a booking is created for a center office, follow up tasks are generated depending on its associated models."
            ]

        ];
    }
}
