<?php
/*
    This file is part of Symbiose Community Edition <https://github.com/yesbabylon/symbiose>
    Some Rights Reserved, Yesbabylon SRL, 2020-2025
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

namespace sale\booking\followup;

class TaskModel extends \core\followup\TaskModel {

    public static function getDescription(): string {
        return "A task is generated from a task model when a booking is created or change status.";
    }

    public static function getColumns(): array {
        return [

            'entity' => [
                'type'              => 'string',
                'description'       => "Namespace of the concerned entity.",
                'default'           => 'sale\booking\Booking'
            ],

            'trigger_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'sale\booking\followup\TaskEvent',
                'description'       => "The trigger event associated with the task model.",
                'required'          => false
            ],

            'deadline_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'sale\booking\followup\TaskEvent',
                'description'       => "The deadline event associated with the task model.",
                'domain'            => ['event_type', '=', 'date_field']
            ],

            'tasks_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'sale\booking\followup\Task',
                'foreign_field'     => 'task_model_id',
                'description'       => "The booking tasks generated by the task model."
            ],

            'center_offices_ids' => [
                'type'              => 'many2many',
                'foreign_object'    => 'identity\CenterOffice',
                'foreign_field'     => 'task_models_ids',
                'rel_table'         => 'identity_center_office_rel_sale_booking_task_model',
                'rel_foreign_key'   => 'center_office_id',
                'rel_local_key'     => 'task_models_id',
                'description'       => "Center offices associated with the task model.",
                'help'              => "When a booking is created for a center office, follow up tasks are generated depending on its associated models."
            ]

        ];
    }

    public static function getConstraints(): array {
        return [

            'entity' => [
                'not_allowed' => [
                    'message'   => 'Entity must be "sale\booking\Booking".',
                    'function'  => function ($entity, $values) {
                        return $entity === 'sale\booking\Booking';
                    }
                ]
            ]

        ];
    }
}
