<?php
/*
    This file is part of the Discope property management software <https://github.com/discope-pms/discope>
    Some Rights Reserved, Discope PMS, 2020-2025
    Original author(s): Yesbabylon SRL
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

namespace sale\camp;

use equal\orm\Model;

class Guardian extends Model {

    public static function getDescription(): string {
        return "Guardian of a child that participate to a camp.";
    }

    public static function getColumns(): array {
        return [

            'firstname' => [
                'type'              => 'string',
                'description'       => "First name of the guardian of the child.",
                'required'          => true
            ],

            'lastname' => [
                'type'              => 'string',
                'description'       => "Last name of the guardian of the child.",
                'required'          => true
            ],

            'email' => [
                'type'              => 'string',
                'result_type'       => 'string',
                'usage'             => 'email',
                'description'       => 'Email of the guardian of the child.',
                'required'          => true
            ],

            'mobile' => [
                'type'              => 'string',
                'usage'             => 'phone',
                'description'       => "Mobile phone number of the child's guardian.",
                'required'          => true
            ],

            'phone' => [
                'type'              => 'string',
                'usage'             => 'phone',
                'description'       => "Fix phone number of the child's guardian."
            ],

            'work_phone' => [
                'type'              => 'string',
                'usage'             => 'phone',
                'description'       => "Work phone number of the child's guardian."
            ],

            'address_street' => [
                'type'              => 'string',
                'description'       => "Street and number of the child's guardian.",
                'required'          => true
            ],

            'address_zip' => [
                'type'              => 'string',
                'description'       => "Zip code of the child's guardian.",
                'required'          => true
            ],

            'address_city' => [
                'type'              => 'string',
                'description'       => "City of the child's guardian.",
                'required'          => true
            ],

            'address_country' => [
                'type'              => 'string',
                'usage'             => 'country/iso-3166:2',
                'description'       => "Country of the child's guardian.",
                'default'           => 'BE',
                'selection'         => [
                    'AF'    => 'Afghanistan',
                    'AX'    => 'Aland Islands',
                    'AL'    => 'Albanie',
                    'DZ'    => 'Algérie',
                    'AS'    => 'American Samoa',
                    'AD'    => 'Andorra',
                    'AO'    => 'Angola',
                    'AI'    => 'Anguilla',
                    'AQ'    => 'Antarctica',
                    'AG'    => 'Antigua And Barbuda',
                    'AR'    => 'Argentina',
                    'AM'    => 'Arménie',
                    'AW'    => 'Aruba',
                    'AU'    => 'Australia',
                    'AT'    => 'Autriche',
                    'AZ'    => 'Azerbaïdjan',
                    'BS'    => 'Bahamas',
                    'BH'    => 'Bahrain',
                    'BD'    => 'Bangladesh',
                    'BB'    => 'Barbados',
                    'BY'    => 'Biélorussie',
                    'BE'    => 'Belgique',
                    'BZ'    => 'Belize',
                    'BJ'    => 'Benin',
                    'BM'    => 'Bermuda',
                    'BT'    => 'Bhutan',
                    'BO'    => 'Bolivia',
                    'BA'    => 'Bosnie-Herzégovine',
                    'BW'    => 'Botswana',
                    'BV'    => 'Bouvet Island',
                    'BR'    => 'Brazil',
                    'IO'    => 'British Indian Ocean Territory',
                    'BN'    => 'Brunei Darussalam',
                    'BG'    => 'Bulgarie',
                    'BF'    => 'Burkina Faso',
                    'BI'    => 'Burundi',
                    'KH'    => 'Cambodia',
                    'CM'    => 'Cameroon',
                    'CA'    => 'Canada',
                    'CV'    => 'Cape Verde',
                    'KY'    => 'Cayman Islands',
                    'CF'    => 'Central African Republic',
                    'TD'    => 'Chad',
                    'CL'    => 'Chile',
                    'CN'    => 'China',
                    'CX'    => 'Christmas Island',
                    'CC'    => 'Cocos (Keeling) Islands',
                    'CO'    => 'Colombia',
                    'KM'    => 'Comoros',
                    'CG'    => 'Congo',
                    'CD'    => 'Congo, Democratic Republic',
                    'CK'    => 'Cook Islands',
                    'CR'    => 'Costa Rica',
                    'CI'    => 'Cote D\'Ivoire',
                    'HR'    => 'Croatie',
                    'CU'    => 'Cuba',
                    'CY'    => 'Chypre',
                    'CZ'    => 'Tchéquie',
                    'DK'    => 'Danemark',
                    'DJ'    => 'Djibouti',
                    'DM'    => 'Dominica',
                    'DO'    => 'Dominican Republic',
                    'EC'    => 'Ecuador',
                    'EG'    => 'Egypte',
                    'SV'    => 'El Salvador',
                    'GQ'    => 'Equatorial Guinea',
                    'ER'    => 'Eritrea',
                    'EE'    => 'Estonie',
                    'ET'    => 'Ethiopia',
                    'FK'    => 'Falkland Islands (Malvinas)',
                    'FO'    => 'Faroe Islands',
                    'FJ'    => 'Fiji',
                    'FI'    => 'Finlande',
                    'FR'    => 'France',
                    'GF'    => 'French Guiana',
                    'PF'    => 'French Polynesia',
                    'TF'    => 'French Southern Territories',
                    'GA'    => 'Gabon',
                    'GM'    => 'Gambia',
                    'GE'    => 'Géorgie',
                    'DE'    => 'Allemagne',
                    'GH'    => 'Ghana',
                    'GI'    => 'Gibraltar',
                    'GR'    => 'Greece',
                    'GL'    => 'Greenland',
                    'GD'    => 'Grenada',
                    'GP'    => 'Guadeloupe',
                    'GU'    => 'Guam',
                    'GT'    => 'Guatemala',
                    'GG'    => 'Guernsey',
                    'GN'    => 'Guinea',
                    'GW'    => 'Guinea-Bissau',
                    'GY'    => 'Guyana',
                    'HT'    => 'Haiti',
                    'HM'    => 'Heard Island & Mcdonald Islands',
                    'VA'    => 'Holy See (Vatican City State)',
                    'HN'    => 'Honduras',
                    'HK'    => 'Hong Kong',
                    'HU'    => 'Hongrie',
                    'IS'    => 'Islande',
                    'IN'    => 'India',
                    'ID'    => 'Indonesia',
                    'IR'    => 'Iran, Islamic Republic Of',
                    'IQ'    => 'Iraq',
                    'IE'    => 'Irlande',
                    'IM'    => 'Isle Of Man',
                    'IL'    => 'Israel',
                    'IT'    => 'Italie',
                    'JM'    => 'Jamaica',
                    'JP'    => 'Japan',
                    'JE'    => 'Jersey',
                    'JO'    => 'Jordanie',
                    'KZ'    => 'Kazakhstan',
                    'KE'    => 'Kenya',
                    'KI'    => 'Kiribati',
                    'KR'    => 'Korea',
                    'KW'    => 'Kuwait',
                    'KG'    => 'Kyrgyzstan',
                    'LA'    => 'Lao People\'s Democratic Republic',
                    'LV'    => 'Lettonie',
                    'LB'    => 'Liban',
                    'LS'    => 'Lesotho',
                    'LR'    => 'Liberia',
                    'LY'    => 'Libye',
                    'LI'    => 'Liechtenstein',
                    'LT'    => 'Lituanie',
                    'LU'    => 'Luxembourg',
                    'MO'    => 'Macao',
                    'MK'    => 'Macedonia',
                    'MG'    => 'Madagascar',
                    'MW'    => 'Malawi',
                    'MY'    => 'Malaysia',
                    'MV'    => 'Maldives',
                    'ML'    => 'Mali',
                    'MT'    => 'Malta',
                    'MH'    => 'Marshall Islands',
                    'MQ'    => 'Martinique',
                    'MR'    => 'Mauritania',
                    'MU'    => 'Mauritius',
                    'YT'    => 'Mayotte',
                    'MX'    => 'Mexico',
                    'FM'    => 'Micronesia, Federated States Of',
                    'MD'    => 'Moldavie',
                    'MC'    => 'Monaco',
                    'MN'    => 'Mongolia',
                    'ME'    => 'Monténégro',
                    'MS'    => 'Montserrat',
                    'MA'    => 'Maroc',
                    'MZ'    => 'Mozambique',
                    'MM'    => 'Myanmar',
                    'NA'    => 'Namibia',
                    'NR'    => 'Nauru',
                    'NP'    => 'Nepal',
                    'NL'    => 'Pays-Bas',
                    'AN'    => 'Netherlands Antilles',
                    'NC'    => 'New Caledonia',
                    'NZ'    => 'New Zealand',
                    'NI'    => 'Nicaragua',
                    'NE'    => 'Niger',
                    'NG'    => 'Nigeria',
                    'NU'    => 'Niue',
                    'NF'    => 'Norfolk Island',
                    'MP'    => 'Northern Mariana Islands',
                    'NO'    => 'Norvège',
                    'OM'    => 'Oman',
                    'PK'    => 'Pakistan',
                    'PW'    => 'Palau',
                    'PS'    => 'Palestinian Territory, Occupied',
                    'PA'    => 'Panama',
                    'PG'    => 'Papua New Guinea',
                    'PY'    => 'Paraguay',
                    'PE'    => 'Peru',
                    'PH'    => 'Philippines',
                    'PN'    => 'Pitcairn',
                    'PL'    => 'Pologne',
                    'PT'    => 'Portugal',
                    'PR'    => 'Puerto Rico',
                    'QA'    => 'Qatar',
                    'RE'    => 'Reunion',
                    'RO'    => 'Roumanie',
                    'RU'    => 'Russie',
                    'RW'    => 'Rwanda',
                    'BL'    => 'Saint Barthelemy',
                    'SH'    => 'Saint Helena',
                    'KN'    => 'Saint Kitts And Nevis',
                    'LC'    => 'Saint Lucia',
                    'MF'    => 'Saint Martin',
                    'PM'    => 'Saint Pierre And Miquelon',
                    'VC'    => 'Saint Vincent And Grenadines',
                    'WS'    => 'Samoa',
                    'SM'    => 'San Marino',
                    'ST'    => 'Sao Tome And Principe',
                    'SA'    => 'Saudi Arabia',
                    'SN'    => 'Senegal',
                    'RS'    => 'Serbie',
                    'SC'    => 'Seychelles',
                    'SL'    => 'Sierra Leone',
                    'SG'    => 'Singapore',
                    'SK'    => 'Slovakia',
                    'SI'    => 'Slovénie',
                    'SB'    => 'Solomon Islands',
                    'SO'    => 'Somalia',
                    'ZA'    => 'South Africa',
                    'GS'    => 'South Georgia And Sandwich Isl.',
                    'ES'    => 'Espagne',
                    'LK'    => 'Sri Lanka',
                    'SD'    => 'Sudan',
                    'SR'    => 'Suriname',
                    'SJ'    => 'Svalbard And Jan Mayen',
                    'SZ'    => 'Swaziland',
                    'SE'    => 'Suède',
                    'CH'    => 'Suisse',
                    'SY'    => 'Syrie',
                    'TW'    => 'Taiwan',
                    'TJ'    => 'Tajikistan',
                    'TZ'    => 'Tanzania',
                    'TH'    => 'Thailand',
                    'TL'    => 'Timor-Leste',
                    'TG'    => 'Togo',
                    'TK'    => 'Tokelau',
                    'TO'    => 'Tonga',
                    'TT'    => 'Trinidad And Tobago',
                    'TN'    => 'Tunisie',
                    'TR'    => 'Turquie',
                    'TM'    => 'Turkmenistan',
                    'TC'    => 'Turks And Caicos Islands',
                    'TV'    => 'Tuvalu',
                    'UG'    => 'Uganda',
                    'UA'    => 'Ukraine',
                    'AE'    => 'United Arab Emirates',
                    'GB'    => 'United Kingdom',
                    'US'    => 'United States',
                    'UM'    => 'United States Outlying Islands',
                    'UY'    => 'Uruguay',
                    'UZ'    => 'Uzbekistan',
                    'VU'    => 'Vanuatu',
                    'VE'    => 'Venezuela',
                    'VN'    => 'Viet Nam',
                    'VG'    => 'Virgin Islands, British',
                    'VI'    => 'Virgin Islands, U.S.',
                    'WF'    => 'Wallis And Futuna',
                    'EH'    => 'Western Sahara',
                    'YE'    => 'Yemen',
                    'ZM'    => 'Zambia',
                    'ZW'    => 'Zimbabwe'
                ],
            ],

            'relation_type' => [
                'type'              => 'string',
                'selection'         => [
                    'mother',
                    'father',
                    'legal_tutor',
                    'family_member',
                    'home_manager'
                ],
                'description'       => "Relation of the person to the guardian.",
                'default'           => 'mother'
            ],

            'children_ids' => [
                'type'              => 'many2many',
                'foreign_object'    => 'sale\camp\Child',
                'foreign_field'     => 'guardians_ids',
                'rel_table'         => 'sale_camp_rel_child_guardian',
                'rel_foreign_key'   => 'child_id',
                'rel_local_key'     => 'guardian_id',
                'description'       => "Children of the guardian."
            ]

        ];
    }
}

